### ISSUE TITLE
Allow rendering of liquid variables in parameters

### ISSUE THREAD

**Issue by ptoews** [rjoberon/bibsonomy-jekyll#1]
Hey @rjoberon!
At my university institute we are currently trying to port the website to jekyll. One important feature is the displaying of each members publications via bibsonomy. So we are really happy that you created this  plugin.

However, one dealbreaking issue is the missing support for liquid variables in the liquid tag parameters, for example:
`{% bibsonomy user {{person_name}} 1000 %}`
This doesn't work because bibsonomy searches for a user called `{{person_name}}`. Leaving out the braces doesn't help either.

**Comment by rjoberon** [comment]
Thank you, that's a good idea. I've implemented this in version 0.1.7.
