### ISSUE TITLE
Allowing multiple disjunctive group tags for query

### ISSUE THREAD

**Issue by raphaelmenges** [rjoberon/bibsonomy-jekyll#3]
Dear @rjoberon,

we are using your plugin to query for publications by members of our institute. We have established the policy to add each author's bibsonomy username as tag to her publication, thus we can simply query for the publications that contain a tag that matches a person's username.

However, due to some legacy policy, one person might have used two or more different tags over time to mark her publications (e.g., first "@username" and later "username"). Is it possible with your plugin to provide multiple tags and match for all them at a query in an disjunctive "OR" manner? This might be also useful, e.g., if somebody wants to filter only for personal publications from certain research fields marked with tags.

Thank you,
@raphaelmenges

**Comment by rjoberon** [comment]
Dear @raphaelmenges 

I understand your request but it's not easy to implement, as (to the best of my knowledge) neither the BibSonomy REST API nor the web application support disjunctive tag queries (only conjunctive queries are supported). Thus, at the moment this could only be implemented by performing several API calls and then merging the results which I consider too much overhead for this small plugin.

Sorry!
